name       : libqxp
version    : 0.0.1
release    : 4
source     :
    - https://dev-www.libreoffice.org/src/libqxp/libqxp-0.0.1.tar.xz : 8c257f6184ff94aefa7c9fa1cfae82083d55a49247266905c71c53e013f95c73
license    : MPL-2.0
component  : programming
summary    : Library for processing QuarkXPress documents
description: |
    libqxp is library providing ability to interpret and import QuarkXPress
    document formats into various applications.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-uc)
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
